<a href="https://colab.research.google.com/github/Anantmishra1907/phythonlearning/blob/main/pandas_missing_value.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checking Missing Values in Pandas

In [1]:
import pandas as pd
import numpy as np

In [4]:
d = {
    'Name':['Abs ' , 'Bcd ' , np.nan],
    'Score' : [12 , np.nan , 14 ]}
df = pd.DataFrame(d)
mv = df.isnull()
print(df)
print(mv)
print(df.isna())

   Name  Score
0  Abs    12.0
1  Bcd     NaN
2   NaN   14.0
    Name  Score
0  False  False
1  False   True
2   True  False
    Name  Score
0  False  False
1  False   True
2   True  False

In [7]:
nmv = df.notnull()

In [8]:
print(nmv)

    Name  Score
0   True   True
1   True  False
2  False   True

Filling Missing Value

In [9]:
import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
dd = pd.DataFrame(d)

dd.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

to fill previous value

In [10]:
df.fillna(method = 'pad')

/tmp/ipykernel_1070/2275225546.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'pad')

   Name  Score
0  Abs    12.0
1  Bcd    12.0
2  Bcd    14.0

In [12]:
dd.fillna(method= 'bfill')

/tmp/ipykernel_1070/4284588863.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dd.fillna(method= 'bfill')

   First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

Dropppimng miossing value

In [13]:
df.dropna()

   Name  Score
0  Abs    12.0